#!/usr/bin/env bash
# Path-scoped convention detection and rule file generation for auto-context
# Provides: detect_path_scope, generate_rule_files, write_overflow_file, cleanup_auto_rules

# detect_path_scope(conv_json)
# Returns a glob pattern if convention is path-scoped, empty string if global
# A convention is path-scoped if ALL evidence files share a common directory prefix at depth >= 2
detect_path_scope() {
  local conv_json="$1"

  # Extract evidence file paths from both evidence[].file and observed_in[]
  local files
  files=$(echo "$conv_json" | jq -r '
    [(.evidence // [])[] | .file // empty] +
    [(.observed_in // [])[] | . // empty] |
    unique | .[]
  ' 2>/dev/null)

  [ -z "$files" ] && return 0

  # Need at least 3 evidence files to consider path-scoping
  local file_count
  file_count=$(echo "$files" | grep -c . 2>/dev/null || echo 0)
  [ "$file_count" -lt 3 ] && return 0

  # Skip bootstrap conventions (project-wide by nature)
  local source
  source=$(echo "$conv_json" | jq -r '.source // ""')
  [ "$source" = "bootstrap" ] && return 0

  # Find common directory prefix
  local common_prefix=""
  while IFS= read -r file_path; do
    [ -z "$file_path" ] && continue
    local dir
    dir=$(dirname "$file_path")
    if [ -z "$common_prefix" ]; then
      common_prefix="$dir"
    else
      # Iteratively shorten prefix until it matches
      while [ "$common_prefix" != "." ] && [ "${dir#"$common_prefix"}" = "$dir" ]; do
        common_prefix=$(dirname "$common_prefix")
      done
    fi
  done <<< "$files"

  # Must be at least 2 levels deep (not root or single top-level dir)
  if [ -z "$common_prefix" ] || [ "$common_prefix" = "." ] || [ "$common_prefix" = "./" ]; then
    return 0
  fi
  local depth
  depth=$(echo "$common_prefix" | tr '/' '\n' | grep -c . 2>/dev/null || echo 0)
  [ "$depth" -lt 2 ] && return 0

  # Return glob pattern
  echo "${common_prefix}/**/*"
}

# generate_rule_files(rules_dir, grouped_convs_json)
# Takes a JSON array of {scope: "glob_pattern", convs: ["text1", "text2"]} groups
# Writes .claude/rules/auto-context-*.md files with paths: YAML frontmatter
# Caps at 5 path-scoped rule files; excess groups merge into overflow
generate_rule_files() {
  local rules_dir="$1" grouped_convs_json="$2"

  local group_count
  group_count=$(echo "$grouped_convs_json" | jq 'length' 2>/dev/null || echo 0)
  [ "$group_count" -eq 0 ] && return 0

  mkdir -p "$rules_dir"

  # If more than 5 groups, split: first 5 get their own files, rest go to overflow
  local main_groups overflow_texts
  if [ "$group_count" -gt 5 ]; then
    main_groups=$(echo "$grouped_convs_json" | jq '.[0:5]')
    overflow_texts=$(echo "$grouped_convs_json" | jq '[.[5:][] | .convs[]] | flatten')
    write_overflow_file "$rules_dir" "$overflow_texts"
  else
    main_groups="$grouped_convs_json"
  fi

  local main_count
  main_count=$(echo "$main_groups" | jq 'length')

  local i=0
  while [ "$i" -lt "$main_count" ]; do
    local group scope dirname_val convs_text
    group=$(echo "$main_groups" | jq ".[$i]")
    scope=$(echo "$group" | jq -r '.scope')
    # Extract deepest directory name for filename
    dirname_val=$(basename "$(echo "$scope" | sed 's|/\*\*/\*$||')")
    convs_text=$(echo "$group" | jq -r '.convs[] | "- " + .')

    [ -z "$convs_text" ] && { i=$((i + 1)); continue; }

    cat > "$rules_dir/auto-context-${dirname_val}.md" << RULEEOF
---
paths:
  - "${scope}"
---

# Auto-Context: ${dirname_val} Conventions

${convs_text}

_Auto-generated by auto-context plugin. Regenerated each session._
RULEEOF

    i=$((i + 1))
  done
}

# write_overflow_file(rules_dir, overflow_texts_json)
# Writes auto-context-overflow.md for global overflow conventions (no paths: frontmatter)
write_overflow_file() {
  local rules_dir="$1" overflow_texts_json="$2"

  local overflow_count
  overflow_count=$(echo "$overflow_texts_json" | jq 'length' 2>/dev/null || echo 0)
  [ "$overflow_count" -eq 0 ] && return 0

  mkdir -p "$rules_dir"

  local convs_text
  convs_text=$(echo "$overflow_texts_json" | jq -r '.[] | "- " + .')

  cat > "$rules_dir/auto-context-overflow.md" << 'OVFEOF'
---
---

# Auto-Context: Overflow Conventions

OVFEOF

  # Append conventions and footer (can't be in heredoc since convs_text is dynamic)
  printf '%s\n\n_Auto-generated by auto-context plugin. Regenerated each session._\n' "$convs_text" >> "$rules_dir/auto-context-overflow.md"
}

# cleanup_auto_rules(rules_dir)
# Removes all auto-context-*.md files in the rules directory
# ONLY removes files matching the auto-context- prefix. Never touches user-created rule files.
cleanup_auto_rules() {
  local rules_dir="$1"
  rm -f "$rules_dir"/auto-context-*.md 2>/dev/null || true
}
